version: '3'
services:
  nginx:
    container_name: nginx
    networks: 
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks: 
      - inception
    build: ./requirements/wordpress
    env_file: .env 
    volumes:
      - wordpress:/var/www/wordpress/html
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/oredoine/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/oredoine/data/mariadb'
